// frontend-vue/src/components/canvas/CanvasEditor.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { api } from "../../api/client";
import { findRelationSnap, portPoint, relationPoints, snap } from "../../domain/geometry";
import { useEditorStore } from "../../stores/editor";
import type { Layout, Point, PortName, Relation, TextBox } from "../../types";

const store = useEditorStore();
const svg = ref<SVGSVGElement | null>(null);
const viewBox = ref({ x: 0, y: 0, width: 1600, height: 1000 });
const snapEnabled = ref(true);
const query = ref("");
const pointer = ref<Point>({ x: 0, y: 0 });
const marquee = ref<{ start: Point; end: Point } | null>(null);
const drag = ref<null | { type: "pan" | "layer" | "resize" | "text" | "resize-text" | "waypoint"; id?: string; index?: number; start: Point; origin: Point; layout?: Layout; text?: TextBox }>(null);
const previewLayouts = ref<Record<string, Layout>>({});
const previewTexts = ref<Record<string, TextBox>>({});
const previewWaypoints = ref<Record<string, Point[]>>({});
const connect = ref<null | { layerId: string; port: PortName; start: Point }>(null);
const relationSnap = ref<ReturnType<typeof findRelationSnap>>(null);

const graph = computed(() => store.displayGraph);
const raw = computed(() => store.graph);
const layouts = computed(() => new Map(graph.value?.layouts.map((row) => [row.layer_id, previewLayouts.value[row.layer_id] ?? row]) ?? []));
const styles = computed(() => new Map(graph.value?.styles.map((row) => [row.layer_id, row]) ?? []));
const relationStyles = computed(() => new Map(graph.value?.relation_styles.map((row) => [row.id, row]) ?? []));
const relations = computed(() => new Map(graph.value?.relations.map((row) => [row.id, previewWaypoints.value[row.id] ? { ...row, waypoints: previewWaypoints.value[row.id] } : row]) ?? []));
const relationPaths = computed(() => graph.value?.relations.map((relation) => ({ relationId: relation.id, points: relationPoints(relations.value.get(relation.id)!, layouts.value, relations.value) })) ?? []);
const selectedLayers = computed(() => new Set(store.selection.filter((row) => row.kind === "layer").map((row) => row.id)));
const selectedRelation = computed(() => store.selection.find((row) => row.kind === "relation")?.id ?? null);
const selectedTexts = computed(() => new Set(store.selection.filter((row) => row.kind === "text").map((row) => row.id)));
const ports: PortName[] = ["top", "right", "bottom", "left"];
const viewBoxString = computed(() => `${viewBox.value.x} ${viewBox.value.y} ${viewBox.value.width} ${viewBox.value.height}`);

function clientPoint(event: PointerEvent | WheelEvent): Point {
  if (svg.value) {
    try {
      const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(svg.value.getScreenCTM()!.inverse());
      return { x: point.x, y: point.y };
    } catch { /* viewBox fallback below */ }
    const rect = svg.value.getBoundingClientRect();
    return { x: viewBox.value.x + (event.clientX - rect.left) / rect.width * viewBox.value.width, y: viewBox.value.y + (event.clientY - rect.top) / rect.height * viewBox.value.height };
  }
  return { x: 0, y: 0 };
}
function nodePointerDown(event: PointerEvent, id: string, resize = false) {
  if (store.mode === "connect") return;
  event.stopPropagation();
  store.select({ kind: "layer", id }, event.ctrlKey || event.metaKey || event.shiftKey);
  const layout = layouts.value.get(id); if (!layout) return;
  drag.value = { type: resize ? "resize" : "layer", id, start: clientPoint(event), origin: { x: layout.x, y: layout.y }, layout: { ...layout } };
  (event.currentTarget as Element).setPointerCapture(event.pointerId);
}
function textPointerDown(event: PointerEvent, row: TextBox, resize = false) {
  if (row.locked) return;
  event.stopPropagation(); store.select({ kind: "text", id: row.id }, event.ctrlKey || event.metaKey);
  drag.value = { type: resize ? "resize-text" : "text", id: row.id, start: clientPoint(event), origin: { x: row.x, y: row.y }, text: { ...row } };
}
function canvasDown(event: PointerEvent) {
  const point = clientPoint(event); pointer.value = point;
  if (event.altKey || event.button === 1) drag.value = { type: "pan", start: { x: event.clientX, y: event.clientY }, origin: { x: viewBox.value.x, y: viewBox.value.y } };
  else if (store.mode === "text") void store.mutateGraph("텍스트 추가", () => api.createText(store.projectId, { text: "Text", x: point.x, y: point.y }));
  else { if (!event.ctrlKey && !event.metaKey) store.selection = []; marquee.value = { start: point, end: point } }
}
function pointerMove(event: PointerEvent) {
  const point = clientPoint(event); pointer.value = point;
  if (connect.value) {
    const candidates = relationPaths.value.filter((path) => path.relationId !== selectedRelation.value);
    relationSnap.value = findRelationSnap(point, candidates, 24 * viewBox.value.width / Math.max(1, svg.value?.clientWidth ?? 1600));
  }
  if (marquee.value) marquee.value.end = point;
  if (!drag.value) return;
  if (drag.value.type === "pan") {
    const scaleX = viewBox.value.width / Math.max(1, svg.value?.clientWidth ?? 1); const scaleY = viewBox.value.height / Math.max(1, svg.value?.clientHeight ?? 1);
    viewBox.value.x = drag.value.origin.x - (event.clientX - drag.value.start.x) * scaleX; viewBox.value.y = drag.value.origin.y - (event.clientY - drag.value.start.y) * scaleY; return;
  }
  const dx = point.x - drag.value.start.x; const dy = point.y - drag.value.start.y;
  if ((drag.value.type === "layer" || drag.value.type === "resize") && drag.value.id && drag.value.layout) {
    const row = { ...drag.value.layout };
    if (drag.value.type === "layer") { row.x = snapEnabled.value ? snap(drag.value.origin.x + dx) : drag.value.origin.x + dx; row.y = snapEnabled.value ? snap(drag.value.origin.y + dy) : drag.value.origin.y + dy }
    else { row.width = Math.max(60, snapEnabled.value ? snap(drag.value.layout.width + dx) : drag.value.layout.width + dx); row.height = Math.max(36, snapEnabled.value ? snap(drag.value.layout.height + dy) : drag.value.layout.height + dy) }
    previewLayouts.value = { ...previewLayouts.value, [drag.value.id]: row };
  } else if ((drag.value.type === "text" || drag.value.type === "resize-text") && drag.value.id && drag.value.text) {
    const next = drag.value.type === "text"
      ? { ...drag.value.text, x: drag.value.origin.x + dx, y: drag.value.origin.y + dy }
      : { ...drag.value.text, width: Math.max(40, drag.value.text.width + dx), height: Math.max(24, drag.value.text.height + dy) };
    previewTexts.value = { ...previewTexts.value, [drag.value.id]: next };
  } else if (drag.value.type === "waypoint" && drag.value.id && drag.value.index !== undefined) {
    const row = relations.value.get(drag.value.id); if (!row) return; const next = [...(row.waypoints ?? [])]; next[drag.value.index] = snapEnabled.value ? { x: snap(point.x), y: snap(point.y) } : point; previewWaypoints.value = { ...previewWaypoints.value, [drag.value.id]: next };
  }
}
async function pointerUp(event: PointerEvent) {
  const point = clientPoint(event);
  if (connect.value) { await finishConnect(point); return }
  if (marquee.value) {
    const { start, end } = marquee.value; const bounds = { x1: Math.min(start.x, end.x), x2: Math.max(start.x, end.x), y1: Math.min(start.y, end.y), y2: Math.max(start.y, end.y) };
    if (Math.abs(start.x - end.x) > 4 || Math.abs(start.y - end.y) > 4) store.selection = graph.value?.layouts.filter((row) => row.x >= bounds.x1 && row.y >= bounds.y1 && row.x + row.width <= bounds.x2 && row.y + row.height <= bounds.y2).map((row) => ({ kind: "layer" as const, id: row.layer_id })) ?? [];
    marquee.value = null;
  }
  const active = drag.value; drag.value = null; if (!active?.id) return;
  const activeId = active.id;
  if ((active.type === "layer" || active.type === "resize") && previewLayouts.value[active.id]) {
    const row = previewLayouts.value[active.id]; previewLayouts.value = {};
    await store.mutateGraph("Layer 배치 저장", () => api.batchGraph(store.projectId, { layouts: [{ layer_id: activeId, x: row.x, y: row.y, width: row.width, height: row.height }] }));
  } else if ((active.type === "text" || active.type === "resize-text") && previewTexts.value[active.id]) {
    const row = previewTexts.value[active.id]; previewTexts.value = {};
    await store.mutateGraph("텍스트 저장", () => api.updateText(store.projectId, active.id!, { x: row.x, y: row.y, width: row.width, height: row.height }));
  } else if (active.type === "waypoint" && previewWaypoints.value[active.id]) {
    const waypoints = previewWaypoints.value[active.id]; previewWaypoints.value = {};
    await store.mutateGraph("Waypoint 저장", () => api.updateRelation(store.projectId, active.id!, { waypoints }));
  }
}
function wheel(event: WheelEvent) {
  event.preventDefault(); const point = clientPoint(event); const factor = event.deltaY > 0 ? 1.12 : 0.88; const width = Math.max(280, Math.min(5000, viewBox.value.width * factor)); const height = width / (viewBox.value.width / viewBox.value.height); const ratioX = (point.x - viewBox.value.x) / viewBox.value.width; const ratioY = (point.y - viewBox.value.y) / viewBox.value.height; viewBox.value = { x: point.x - width * ratioX, y: point.y - height * ratioY, width, height };
}
function startConnect(event: PointerEvent, layerId: string, port: PortName) { event.stopPropagation(); const layout = layouts.value.get(layerId); if (!layout) return; connect.value = { layerId, port, start: portPoint(layout, port) }; pointer.value = clientPoint(event) }
async function finishPort(event: PointerEvent, layerId: string, port: PortName) { event.stopPropagation(); if (!connect.value || connect.value.layerId === layerId) return; const source = connect.value; connect.value = null; relationSnap.value = null; await store.mutateGraph("관계 생성", () => api.createRelation(store.projectId, { parent_layer_id: source.layerId, child_layer_id: layerId, source_port: source.port, target_port: port, relation_style_id: store.selectedRelationStyleId || null })) }
async function finishConnect(_point: Point) { const source = connect.value; const target = relationSnap.value; connect.value = null; relationSnap.value = null; if (source && target) await store.mutateGraph("관계선 연결", () => api.createRelation(store.projectId, { parent_layer_id: source.layerId, child_layer_id: null, source_port: source.port, attached_relation_id: target.relationId, relation_style_id: store.selectedRelationStyleId || null })) }
function relationPolyline(relation: Relation) { return relationPoints(relations.value.get(relation.id)!, layouts.value, relations.value).map((point) => `${point.x},${point.y}`).join(" ") }
function dash(relation: Relation) { const style = relation.relation_style_id ? relationStyles.value.get(relation.relation_style_id) : undefined; return style?.line_pattern === "dashed" ? "10 7" : style?.line_pattern === "dotted" ? "2 6" : style?.line_pattern === "reference" ? "12 6 2 6" : undefined }
async function addWaypoint(event: MouseEvent, relation: Relation) { event.stopPropagation(); const point = clientPoint(event as unknown as PointerEvent); await store.mutateGraph("Waypoint 추가", () => api.updateRelation(store.projectId, relation.id, { waypoints: [...(relation.waypoints ?? []), point] })) }
function waypointDown(event: PointerEvent, relation: Relation, index: number) { event.stopPropagation(); drag.value = { type: "waypoint", id: relation.id, index, start: clientPoint(event), origin: { x: 0, y: 0 } }; store.select({ kind: "relation", id: relation.id }) }
async function deleteWaypoint(event: MouseEvent, relation: Relation, index: number) { event.preventDefault(); event.stopPropagation(); await store.mutateGraph("Waypoint 삭제", () => api.updateRelation(store.projectId, relation.id, { waypoints: relation.waypoints.filter((_point, pointIndex) => pointIndex !== index) })) }
function focusSearch() { const layer = graph.value?.layers.find((row) => row.name.toLowerCase().includes(query.value.toLowerCase())); const layout = layer ? layouts.value.get(layer.id) : null; if (layout) { viewBox.value = { x: layout.x - 320, y: layout.y - 220, width: 800, height: 500 }; store.select({ kind: "layer", id: layer!.id }) } }
async function editLayer(id: string) { const layer = raw.value?.layers.find((row) => row.id === id); if (!layer) return; const name = prompt("Layer 이름", layer.name); if (!name?.trim()) return; const step = prompt("Step", layer.step ?? ""); await store.mutateGraph("Layer 인라인 저장", () => api.updateLayer(store.projectId, id, { name: name.trim(), step: step?.trim() || null })) }
function fit() { viewBox.value = { x: 0, y: 0, width: 1600, height: 1000 } }
</script>

<template>
  <div class="canvas-pane">
    <div class="canvas-float"><input v-model="query" placeholder="Layer 검색" @keydown.enter="focusSearch"><button @click="focusSearch">찾기</button><button @click="fit">전체 보기</button><label><input v-model="snapEnabled" type="checkbox">20px Snap</label></div>
    <svg ref="svg" class="canvas" :class="`${store.mode}-mode`" :viewBox="viewBoxString" @pointerdown="canvasDown" @pointermove="pointerMove" @pointerup="pointerUp" @pointercancel="pointerUp" @wheel="wheel">
      <defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M 20 0 L 0 0 0 20" fill="none" stroke="#e9edf3" stroke-width="1"/></pattern><marker id="arrow" markerWidth="10" markerHeight="8" refX="9" refY="4" orient="auto"><path d="M0,0 L10,4 L0,8 Z" fill="context-stroke"/></marker></defs>
      <rect :x="viewBox.x" :y="viewBox.y" :width="viewBox.width" :height="viewBox.height" fill="url(#grid)"/>
      <g v-for="relation in graph?.relations" :key="relation.id" class="relation-group" @click.stop="store.select({ kind: 'relation', id: relation.id })" @dblclick="addWaypoint($event, relation)">
        <polyline class="relation-hit" :points="relationPolyline(relation)"/>
        <polyline class="relation-line" :class="{ selected: selectedRelation === relation.id }" :points="relationPolyline(relation)" fill="none" :stroke="relationStyles.get(relation.relation_style_id || '')?.stroke_color || '#475467'" :stroke-width="relationStyles.get(relation.relation_style_id || '')?.stroke_width || 2" :stroke-dasharray="dash(relation)" marker-end="url(#arrow)"/>
        <circle v-for="(point, index) in (previewWaypoints[relation.id] || relation.waypoints)" :key="index" class="waypoint" :cx="point.x" :cy="point.y" r="7" @pointerdown="waypointDown($event, relation, index)" @contextmenu="deleteWaypoint($event, relation, index)"/>
      </g>
      <polyline v-if="connect" class="connect-preview" :points="`${connect.start.x},${connect.start.y} ${relationSnap?.point.x ?? pointer.x},${relationSnap?.point.y ?? pointer.y}`"/>
      <circle v-if="relationSnap" class="snap-dot" :cx="relationSnap.point.x" :cy="relationSnap.point.y" r="9"/>
      <g v-for="layer in graph?.layers" :key="layer.id" class="layer-node" :class="{ selected: selectedLayers.has(layer.id) }" @pointerdown="nodePointerDown($event, layer.id)" @dblclick.stop="editLayer(layer.id)">
        <template v-if="layouts.get(layer.id)"><rect :x="layouts.get(layer.id)!.x" :y="layouts.get(layer.id)!.y" :width="layouts.get(layer.id)!.width" :height="layouts.get(layer.id)!.height" rx="12" :fill="styles.get(layer.id)?.fill_color || '#fff'" :stroke="styles.get(layer.id)?.stroke_color || '#175cd3'" :stroke-width="styles.get(layer.id)?.stroke_width || 2"/><text :x="layouts.get(layer.id)!.x + layouts.get(layer.id)!.width / 2" :y="layouts.get(layer.id)!.y + layouts.get(layer.id)!.height / 2" text-anchor="middle" dominant-baseline="middle" :fill="styles.get(layer.id)?.text_color || '#101828'" :font-size="styles.get(layer.id)?.font_size || 14"><tspan v-for="(line, index) in layer.name.split('\n')" :key="index" :x="layouts.get(layer.id)!.x + layouts.get(layer.id)!.width / 2" :dy="index ? 18 : -(layer.name.split('\n').length - 1) * 9">{{ line }}</tspan></text>
          <template v-if="selectedLayers.has(layer.id) || store.mode === 'connect'"><g v-for="port in ports" :key="port"><circle class="port" :cx="portPoint(layouts.get(layer.id)!, port).x" :cy="portPoint(layouts.get(layer.id)!, port).y" r="8" @pointerdown="startConnect($event, layer.id, port)" @pointerup="finishPort($event, layer.id, port)"/></g></template>
          <rect v-if="selectedLayers.has(layer.id) && store.mode === 'select'" class="resize-handle" :x="layouts.get(layer.id)!.x + layouts.get(layer.id)!.width - 6" :y="layouts.get(layer.id)!.y + layouts.get(layer.id)!.height - 6" width="12" height="12" @pointerdown="nodePointerDown($event, layer.id, true)"/>
        </template>
      </g>
      <g v-for="text in graph?.text_boxes" :key="text.id" class="text-box" :class="{ selected: selectedTexts.has(text.id) }" @pointerdown="textPointerDown($event, previewTexts[text.id] || text)"><rect :x="(previewTexts[text.id] || text).x" :y="(previewTexts[text.id] || text).y" :width="(previewTexts[text.id] || text).width" :height="(previewTexts[text.id] || text).height" :fill="text.background_color" :stroke="text.border_color"/><text :x="(previewTexts[text.id] || text).x + 8" :y="(previewTexts[text.id] || text).y + (previewTexts[text.id] || text).height / 2" dominant-baseline="middle" :fill="text.text_color" :font-size="text.font_size">{{ text.text }}</text><rect v-if="selectedTexts.has(text.id) && !text.locked" class="resize-handle" :x="(previewTexts[text.id] || text).x + (previewTexts[text.id] || text).width - 6" :y="(previewTexts[text.id] || text).y + (previewTexts[text.id] || text).height - 6" width="12" height="12" @pointerdown.stop="textPointerDown($event, previewTexts[text.id] || text, true)"/></g>
      <rect v-if="marquee" class="marquee" :x="Math.min(marquee.start.x, marquee.end.x)" :y="Math.min(marquee.start.y, marquee.end.y)" :width="Math.abs(marquee.end.x - marquee.start.x)" :height="Math.abs(marquee.end.y - marquee.start.y)"/>
    </svg>
    <svg v-if="graph" class="minimap" viewBox="0 0 1600 1000"><rect width="1600" height="1000" fill="#f8fafc"/><rect v-for="layout in graph.layouts" :key="layout.id" :x="layout.x" :y="layout.y" :width="layout.width" :height="layout.height" rx="8" fill="#84adff"/><rect :x="viewBox.x" :y="viewBox.y" :width="viewBox.width" :height="viewBox.height" fill="none" stroke="#175cd3" stroke-width="10"/></svg>
    <div class="canvas-hint">Alt + 드래그 이동 · 휠 확대/축소 · 관계선 더블클릭 waypoint · 우클릭 waypoint 삭제</div>
  </div>
</template>

// frontend/src/components/CanvasEditor.tsx
import { useMemo, useRef, useState } from "react";
import type React from "react";
import type { EditorMode, Graph, GraphBatchUpdate, Layout, PortName, RelationStyle, SelectionItem, TextBox } from "../types";

interface Props {
  graph: Graph | null;
  selection: SelectionItem[];
  mode: EditorMode;
  selectedRelationStyleId: string;
  onModeChange: (mode: EditorMode) => void;
  onSelectionChange: (selection: SelectionItem[]) => void;
  onSelectItem: (item: SelectionItem, additive?: boolean) => void;
  onCreateLayer: (x: number, y: number) => void;
  onCreateTextBox: (x: number, y: number) => void;
  onUpdateLayout: (layerId: string, payload: Partial<Layout>) => Promise<void>;
  onUpdateTextBox: (textBoxId: string, payload: Partial<TextBox>) => Promise<void>;
  onUpdateBatch: (payload: GraphBatchUpdate) => Promise<void>;
  onCreateRelation: (payload: Record<string, unknown>) => Promise<void>;
}

interface Point {
  x: number;
  y: number;
}

type DragState =
  | { type: "pan"; clientStart: Point; viewStart: Point }
  | { type: "marquee"; start: Point; current: Point }
  | {
      type: "move";
      start: Point;
      current: Point;
      layerIds: string[];
      textIds: string[];
      layerOrigins: Record<string, Layout>;
      textOrigins: Record<string, TextBox>;
    }
  | { type: "resize-layer"; start: Point; current: Point; layerId: string; origin: Layout }
  | { type: "resize-text"; start: Point; current: Point; textBoxId: string; origin: TextBox };

interface ConnectStart {
  layerId: string;
  port: PortName;
}

const PORTS: PortName[] = ["top", "right", "bottom", "left"];
const GRID_SIZE = 20;

function portPoint(layout: Layout, port: PortName): Point {
  if (port === "top") return { x: layout.x + layout.width / 2, y: layout.y };
  if (port === "right") return { x: layout.x + layout.width, y: layout.y + layout.height / 2 };
  if (port === "bottom") return { x: layout.x + layout.width / 2, y: layout.y + layout.height };
  return { x: layout.x, y: layout.y + layout.height / 2 };
}

function portHandlePoint(layout: Layout, port: PortName): Point {
  const point = portPoint(layout, port);
  const offset = 18;
  if (port === "top") return { x: point.x, y: point.y - offset };
  if (port === "right") return { x: point.x + offset, y: point.y };
  if (port === "bottom") return { x: point.x, y: point.y + offset };
  return { x: point.x - offset, y: point.y };
}

function snap(value: number, enabled: boolean) {
  return enabled ? Math.round(value / GRID_SIZE) * GRID_SIZE : value;
}

function intersects(a: { x: number; y: number; width: number; height: number }, b: { x: number; y: number; width: number; height: number }) {
  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;
}

function relationStroke(type: string, style?: RelationStyle) {
  if (style) {
    const dash =
      style.line_pattern === "dashed"
        ? "8 6"
        : style.line_pattern === "dotted"
          ? "2 6"
          : style.line_pattern === "reference"
            ? "10 4 2 4"
            : undefined;
    return {
      strokeDasharray: dash,
      stroke: style.stroke_color,
      strokeWidth: style.stroke_width,
      markerEnd: style.marker_type === "arrow" ? `url(#arrow-${style.id})` : undefined
    };
  }
  const normalized = type.toLowerCase();
  if (normalized === "reference") return { strokeDasharray: "10 4 2 4", stroke: "#7c3aed", strokeWidth: 2, markerEnd: "url(#arrow-reference)" };
  if (normalized === "optional" || normalized === "warning") return { strokeDasharray: "2 5", stroke: "#0891b2", strokeWidth: 2, markerEnd: "url(#arrow-optional)" };
  if (normalized === "overlay") return { strokeDasharray: undefined, stroke: "#f97316", strokeWidth: 2, markerEnd: "url(#arrow-overlay)" };
  return { strokeDasharray: undefined, stroke: "#334155", strokeWidth: 2, markerEnd: "url(#arrow-default)" };
}

export default function CanvasEditor({
  graph,
  selection,
  mode,
  selectedRelationStyleId,
  onModeChange,
  onSelectionChange,
  onSelectItem,
  onCreateLayer,
  onCreateTextBox,
  onUpdateLayout,
  onUpdateTextBox,
  onUpdateBatch,
  onCreateRelation
}: Props) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const [viewBox, setViewBox] = useState({ x: 0, y: 0, width: 1600, height: 1000 });
  const [drag, setDrag] = useState<DragState | null>(null);
  const [connectStart, setConnectStart] = useState<ConnectStart | null>(null);
  const [pointerCanvas, setPointerCanvas] = useState<Point | null>(null);
  const [snapToGrid, setSnapToGrid] = useState(true);
  const [search, setSearch] = useState("");

  const selectedLayerIds = useMemo(
    () => new Set(selection.filter((item) => item.kind === "layer").map((item) => item.id)),
    [selection]
  );
  const selectedTextIds = useMemo(
    () => new Set(selection.filter((item) => item.kind === "text").map((item) => item.id)),
    [selection]
  );
  const selectedRelationIds = useMemo(
    () => new Set(selection.filter((item) => item.kind === "relation").map((item) => item.id)),
    [selection]
  );

  const layoutByLayer = useMemo(() => {
    const map = new Map<string, Layout>();
    graph?.layouts.forEach((layout) => map.set(layout.layer_id, layout));
    return map;
  }, [graph]);

  const graphBounds = useMemo(() => {
    const boxes = [...(graph?.layouts ?? []), ...(graph?.text_boxes ?? [])];
    if (!boxes.length) {
      return { x: 0, y: 0, width: 1600, height: 1000 };
    }
    const minX = Math.min(...boxes.map((box) => box.x));
    const minY = Math.min(...boxes.map((box) => box.y));
    const maxX = Math.max(...boxes.map((box) => box.x + box.width));
    const maxY = Math.max(...boxes.map((box) => box.y + box.height));
    return {
      x: minX - 120,
      y: minY - 120,
      width: Math.max(500, maxX - minX + 240),
      height: Math.max(320, maxY - minY + 240)
    };
  }, [graph]);

  const styleByLayer = useMemo(() => {
    const map = new Map();
    graph?.styles.forEach((style) => map.set(style.layer_id, style));
    return map;
  }, [graph]);

  const relationStyleById = useMemo(() => {
    const map = new Map<string, RelationStyle>();
    graph?.relation_styles.forEach((style) => map.set(style.id, style));
    return map;
  }, [graph]);

  const zoomPercent = Math.round((1600 / viewBox.width) * 100);

  const toCanvasPoint = (event: React.PointerEvent<SVGElement> | React.WheelEvent<SVGSVGElement>): Point => {
    const svg = svgRef.current;
    if (!svg) {
      return { x: 0, y: 0 };
    }
    const transform = svg.getScreenCTM();
    if (transform) {
      const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(transform.inverse());
      return { x: point.x, y: point.y };
    }
    const rect = svg.getBoundingClientRect();
    return {
      x: viewBox.x + ((event.clientX - rect.left) / rect.width) * viewBox.width,
      y: viewBox.y + ((event.clientY - rect.top) / rect.height) * viewBox.height
    };
  };

  const displayLayout = (layout: Layout): Layout => {
    if (drag?.type === "move" && drag.layerOrigins[layout.layer_id]) {
      const origin = drag.layerOrigins[layout.layer_id];
      return { ...origin, x: origin.x + drag.current.x - drag.start.x, y: origin.y + drag.current.y - drag.start.y };
    }
    if (drag?.type === "resize-layer" && drag.layerId === layout.layer_id) {
      return {
        ...layout,
        width: Math.max(60, drag.origin.width + drag.current.x - drag.start.x),
        height: Math.max(36, drag.origin.height + drag.current.y - drag.start.y)
      };
    }
    return layout;
  };

  const displayTextBox = (textBox: TextBox): TextBox => {
    if (drag?.type === "move" && drag.textOrigins[textBox.id]) {
      const origin = drag.textOrigins[textBox.id];
      return { ...origin, x: origin.x + drag.current.x - drag.start.x, y: origin.y + drag.current.y - drag.start.y };
    }
    if (drag?.type === "resize-text" && drag.textBoxId === textBox.id) {
      return {
        ...textBox,
        width: Math.max(40, drag.origin.width + drag.current.x - drag.start.x),
        height: Math.max(24, drag.origin.height + drag.current.y - drag.start.y)
      };
    }
    return textBox;
  };

  const beginMove = (event: React.PointerEvent<SVGElement>, item: SelectionItem) => {
    if (!graph) return;
    if (event.altKey) {
      event.stopPropagation();
      setDrag({ type: "pan", clientStart: { x: event.clientX, y: event.clientY }, viewStart: { x: viewBox.x, y: viewBox.y } });
      return;
    }
    const additive = event.ctrlKey || event.metaKey || event.shiftKey;
    const isAlreadySelected = selection.some((selected) => selected.kind === item.kind && selected.id === item.id);
    if (!isAlreadySelected || additive) {
      onSelectItem(item, additive);
    }
    const activeSelection = isAlreadySelected ? selection : additive ? [...selection, item] : [item];
    const layerIds = activeSelection.filter((selected) => selected.kind === "layer").map((selected) => selected.id);
    const textIds = activeSelection.filter((selected) => selected.kind === "text").map((selected) => selected.id);
    const layerOrigins = Object.fromEntries(
      layerIds
        .map((id) => layoutByLayer.get(id))
        .filter((layout): layout is Layout => Boolean(layout))
        .map((layout) => [layout.layer_id, layout])
    ) as Record<string, Layout>;
    const textOrigins = Object.fromEntries(
      textIds
        .map((id) => graph.text_boxes.find((textBox) => textBox.id === id))
        .filter((textBox): textBox is TextBox => Boolean(textBox))
        .map((textBox) => [textBox.id, textBox])
    ) as Record<string, TextBox>;
    const point = toCanvasPoint(event);
    setDrag({ type: "move", start: point, current: point, layerIds, textIds, layerOrigins, textOrigins });
  };

  const handleBackgroundPointerDown = (event: React.PointerEvent<SVGSVGElement>) => {
    if (event.target !== event.currentTarget && !(event.target instanceof SVGRectElement && event.target.classList.contains("canvas-bg"))) return;
    const point = toCanvasPoint(event);
    if (event.altKey) {
      setDrag({ type: "pan", clientStart: { x: event.clientX, y: event.clientY }, viewStart: { x: viewBox.x, y: viewBox.y } });
      return;
    }
    if (mode === "text") {
      onCreateTextBox(point.x, point.y);
      onModeChange("select");
      return;
    }
    setConnectStart(null);
    onSelectionChange([]);
    setDrag({ type: "marquee", start: point, current: point });
  };

  const handlePointerMove = (event: React.PointerEvent<SVGSVGElement>) => {
    setPointerCanvas(toCanvasPoint(event));
    if (!drag) return;
    if (drag.type === "pan") {
      const svg = svgRef.current;
      if (!svg) return;
      const rect = svg.getBoundingClientRect();
      const dx = ((event.clientX - drag.clientStart.x) / rect.width) * viewBox.width;
      const dy = ((event.clientY - drag.clientStart.y) / rect.height) * viewBox.height;
      setViewBox((current) => ({ ...current, x: drag.viewStart.x - dx, y: drag.viewStart.y - dy }));
      return;
    }
    setDrag({ ...drag, current: toCanvasPoint(event) } as DragState);
  };

  const handlePointerUp = () => {
    if (!graph || !drag) {
      setDrag(null);
      return;
    }

    if (drag.type === "marquee") {
      const rect = {
        x: Math.min(drag.start.x, drag.current.x),
        y: Math.min(drag.start.y, drag.current.y),
        width: Math.abs(drag.current.x - drag.start.x),
        height: Math.abs(drag.current.y - drag.start.y)
      };
      const nextSelection: SelectionItem[] = [];
      graph.layers.forEach((layer) => {
        const layout = layoutByLayer.get(layer.id);
        if (layout && intersects(rect, layout)) {
          nextSelection.push({ kind: "layer", id: layer.id });
        }
      });
      graph.text_boxes.forEach((textBox) => {
        if (intersects(rect, textBox)) {
          nextSelection.push({ kind: "text", id: textBox.id });
        }
      });
      onSelectionChange(nextSelection);
    }

    if (drag.type === "move") {
      const dx = drag.current.x - drag.start.x;
      const dy = drag.current.y - drag.start.y;
      void onUpdateBatch({
        layouts: Object.values(drag.layerOrigins).map((layout) => ({
          layer_id: layout.layer_id,
          x: Math.round(snap(layout.x + dx, snapToGrid)),
          y: Math.round(snap(layout.y + dy, snapToGrid))
        })),
        text_boxes: Object.values(drag.textOrigins).map((textBox) => ({
          id: textBox.id,
          x: Math.round(snap(textBox.x + dx, snapToGrid)),
          y: Math.round(snap(textBox.y + dy, snapToGrid))
        }))
      });
    }

    if (drag.type === "resize-layer") {
      const width = Math.round(snap(Math.max(60, drag.origin.width + drag.current.x - drag.start.x), snapToGrid));
      const height = Math.round(snap(Math.max(36, drag.origin.height + drag.current.y - drag.start.y), snapToGrid));
      void onUpdateLayout(drag.layerId, { width, height });
    }

    if (drag.type === "resize-text") {
      const width = Math.round(snap(Math.max(40, drag.origin.width + drag.current.x - drag.start.x), snapToGrid));
      const height = Math.round(snap(Math.max(24, drag.origin.height + drag.current.y - drag.start.y), snapToGrid));
      void onUpdateTextBox(drag.textBoxId, { width, height });
    }

    setDrag(null);
  };

  const handleWheel = (event: React.WheelEvent<SVGSVGElement>) => {
    event.preventDefault();
    const factor = event.deltaY > 0 ? 1.08 : 0.92;
    const point = toCanvasPoint(event);
    setViewBox((current) => {
      const width = Math.min(3600, Math.max(360, current.width * factor));
      const height = Math.min(2400, Math.max(240, current.height * factor));
      return {
        x: point.x - ((point.x - current.x) / current.width) * width,
        y: point.y - ((point.y - current.y) / current.height) * height,
        width,
        height
      };
    });
  };

  const handlePortClick = (event: React.PointerEvent<SVGCircleElement>, layerId: string, port: PortName) => {
    event.stopPropagation();
    if (!connectStart) {
      setConnectStart({ layerId, port });
      onSelectionChange([{ kind: "layer", id: layerId }]);
      onModeChange("connect");
      return;
    }
    if (connectStart.layerId !== layerId) {
      void onCreateRelation({
        parent_layer_id: connectStart.layerId,
        child_layer_id: layerId,
        source_port: connectStart.port,
        target_port: port,
        relation_type: relationStyleById.get(selectedRelationStyleId)?.name ?? "Align",
        relation_style_id: selectedRelationStyleId || null
      });
    }
    setConnectStart(null);
    onModeChange("select");
  };

  const fitView = () => {
    if (!graph || graph.layouts.length === 0) return;
    setViewBox({ ...graphBounds });
  };

  const focusLayer = (layerId: string) => {
    const layout = layoutByLayer.get(layerId);
    if (!layout) return;
    onSelectionChange([{ kind: "layer", id: layerId }]);
    setViewBox((current) => ({
      ...current,
      x: layout.x + layout.width / 2 - current.width / 2,
      y: layout.y + layout.height / 2 - current.height / 2
    }));
  };

  const searchLayer = () => {
    const normalized = search.trim().toLowerCase();
    if (!normalized || !graph) return;
    const layer = graph.layers.find((item) => item.name.toLowerCase().includes(normalized));
    if (layer) focusLayer(layer.id);
  };

  const marquee =
    drag?.type === "marquee"
      ? {
          x: Math.min(drag.start.x, drag.current.x),
          y: Math.min(drag.start.y, drag.current.y),
          width: Math.abs(drag.current.x - drag.start.x),
          height: Math.abs(drag.current.y - drag.start.y)
        }
      : null;

  return (
    <section className="canvas-pane">
      <div className="canvas-actions">
        <button type="button" onClick={fitView}>Fit</button>
        <button type="button" onClick={() => setViewBox((current) => ({ ...current, width: current.width * 0.9, height: current.height * 0.9 }))}>
          Zoom In
        </button>
        <button type="button" onClick={() => setViewBox((current) => ({ ...current, width: current.width * 1.1, height: current.height * 1.1 }))}>
          Zoom Out
        </button>
        <span className="zoom-label">{zoomPercent}%</span>
        <label className="snap-toggle"><input type="checkbox" checked={snapToGrid} onChange={(event) => setSnapToGrid(event.target.checked)} /> Snap</label>
        <input
          className="canvas-search"
          value={search}
          onChange={(event) => setSearch(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter") searchLayer();
          }}
          placeholder="Search layer"
        />
        <button type="button" onClick={searchLayer}>Find</button>
      </div>
      <div className="mode-hint">
        {connectStart ? "Connector: choose target point" : mode === "connect" ? "Connector Mode" : "Select Mode"}
      </div>
      <svg
        ref={svgRef}
        className={mode === "connect" ? "canvas connect-mode" : "canvas"}
        viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`}
        onPointerDown={handleBackgroundPointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
        onPointerLeave={handlePointerUp}
        onWheel={handleWheel}
      >
        <defs>
          <pattern id="grid" width={GRID_SIZE} height={GRID_SIZE} patternUnits="userSpaceOnUse">
            <path d={`M ${GRID_SIZE} 0 L 0 0 0 ${GRID_SIZE}`} fill="none" stroke="#e5e7eb" strokeWidth="1" />
          </pattern>
          {[
            ["default", "#334155"],
            ["reference", "#7c3aed"],
            ["optional", "#0891b2"],
            ["overlay", "#f97316"]
          ].map(([id, color]) => (
            <marker key={id} id={`arrow-${id}`} markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 0 0 L 10 5 L 0 10 z" fill={color} />
            </marker>
          ))}
          {graph?.relation_styles.map((style) => (
            <marker key={style.id} id={`arrow-${style.id}`} markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto" markerUnits="userSpaceOnUse">
              <path d="M 0 0 L 10 5 L 0 10 z" fill={style.stroke_color} />
            </marker>
          ))}
        </defs>
        <rect className="canvas-bg" x={viewBox.x - 2000} y={viewBox.y - 2000} width={viewBox.width + 4000} height={viewBox.height + 4000} fill="url(#grid)" />
        {graph?.relations.map((relation) => {
          const source = layoutByLayer.get(relation.parent_layer_id);
          const target = layoutByLayer.get(relation.child_layer_id);
          if (!source || !target) return null;
          const sourceLayout = displayLayout(source);
          const targetLayout = displayLayout(target);
          const a = portPoint(sourceLayout, relation.source_port);
          const b = portPoint(targetLayout, relation.target_port);
          const style = relationStroke(relation.relation_type, relation.relation_style_id ? relationStyleById.get(relation.relation_style_id) : undefined);
          return (
            <g key={relation.id}>
              <line
                className={selectedRelationIds.has(relation.id) ? "relation selected" : "relation"}
                x1={a.x}
                y1={a.y}
                x2={b.x}
                y2={b.y}
                stroke={style.stroke}
                strokeWidth={style.strokeWidth}
                strokeDasharray={style.strokeDasharray}
                markerEnd={style.markerEnd}
              />
              <line
                className="relation-hit"
                x1={a.x}
                y1={a.y}
                x2={b.x}
                y2={b.y}
                onPointerDown={(event) => {
                  event.stopPropagation();
                  onSelectItem({ kind: "relation", id: relation.id }, event.ctrlKey || event.metaKey || event.shiftKey);
                }}
              />
            </g>
          );
        })}
        {connectStart && pointerCanvas && (() => {
          const source = layoutByLayer.get(connectStart.layerId);
          if (!source) return null;
          const start = portHandlePoint(displayLayout(source), connectStart.port);
          return <line className="connector-preview" x1={start.x} y1={start.y} x2={pointerCanvas.x} y2={pointerCanvas.y} />;
        })()}
        {graph?.text_boxes.map((textBox) => {
          const box = displayTextBox(textBox);
          const selected = selectedTextIds.has(textBox.id);
          return (
            <g key={textBox.id} className={selected ? "text-box selected" : "text-box"} onPointerDown={(event) => beginMove(event, { kind: "text", id: textBox.id })}>
              <rect x={box.x} y={box.y} width={box.width} height={box.height} fill={box.background_color} stroke={box.border_color} rx="3" />
              <text x={box.x + 12} y={box.y + box.height / 2 + box.font_size / 3} fill={box.text_color} fontSize={box.font_size}>
                {box.text}
              </text>
              {selected && (
                <rect
                  className="resize-handle"
                  x={box.x + box.width - 8}
                  y={box.y + box.height - 8}
                  width="12"
                  height="12"
                  onPointerDown={(event) => {
                    event.stopPropagation();
                    const point = toCanvasPoint(event);
                    setDrag({ type: "resize-text", start: point, current: point, textBoxId: textBox.id, origin: textBox });
                  }}
                />
              )}
            </g>
          );
        })}
        {graph?.layers.map((layer) => {
          const baseLayout = layoutByLayer.get(layer.id);
          if (!baseLayout) return null;
          const layout = displayLayout(baseLayout);
          const style = styleByLayer.get(layer.id);
          const selected = selectedLayerIds.has(layer.id);
          const showPorts = selected || mode === "connect" || Boolean(connectStart);
          return (
            <g key={layer.id} className={selected ? "layer-node selected" : "layer-node"} onPointerDown={(event) => beginMove(event, { kind: "layer", id: layer.id })}>
              <rect
                x={layout.x}
                y={layout.y}
                width={layout.width}
                height={layout.height}
                rx="6"
                fill={style?.fill_color ?? "#ffffff"}
                stroke={style?.stroke_color ?? "#2563eb"}
                strokeWidth={style?.stroke_width ?? 2}
              />
              <text
                x={layout.x + layout.width / 2}
                y={layout.y + layout.height / 2 + (style?.font_size ?? 14) / 3}
                textAnchor="middle"
                fill={style?.text_color ?? "#111827"}
                fontSize={style?.font_size ?? 14}
              >
                {layer.name}
              </text>
              {showPorts &&
                PORTS.map((port) => {
                  const anchor = portPoint(layout, port);
                  const point = portHandlePoint(layout, port);
                  return (
                    <g key={port}>
                      <line className="port-stem" x1={anchor.x} y1={anchor.y} x2={point.x} y2={point.y} />
                      <circle
                        className={connectStart ? "port connectable" : "port"}
                        cx={point.x}
                        cy={point.y}
                        r="7"
                        onPointerDown={(event) => handlePortClick(event, layer.id, port)}
                      />
                    </g>
                  );
                })}
              {selected && (
                <rect
                  className="resize-handle"
                  x={layout.x + layout.width - 8}
                  y={layout.y + layout.height - 8}
                  width="12"
                  height="12"
                  onPointerDown={(event) => {
                    event.stopPropagation();
                    const point = toCanvasPoint(event);
                    setDrag({ type: "resize-layer", start: point, current: point, layerId: layer.id, origin: baseLayout });
                  }}
                />
              )}
            </g>
          );
        })}
        {marquee && <rect className="marquee" x={marquee.x} y={marquee.y} width={marquee.width} height={marquee.height} />}
      </svg>
      <svg className="mini-map" viewBox={`${graphBounds.x} ${graphBounds.y} ${graphBounds.width} ${graphBounds.height}`} aria-label="Mini map">
        <rect x={graphBounds.x} y={graphBounds.y} width={graphBounds.width} height={graphBounds.height} fill="#f8fafc" />
        {graph?.relations.map((relation) => {
          const source = layoutByLayer.get(relation.parent_layer_id);
          const target = layoutByLayer.get(relation.child_layer_id);
          if (!source || !target) return null;
          return (
            <line
              key={relation.id}
              x1={source.x + source.width / 2}
              y1={source.y + source.height / 2}
              x2={target.x + target.width / 2}
              y2={target.y + target.height / 2}
              stroke="#94a3b8"
              strokeWidth="6"
            />
          );
        })}
        {graph?.layouts.map((layout) => (
          <rect
            key={layout.layer_id}
            x={layout.x}
            y={layout.y}
            width={layout.width}
            height={layout.height}
            fill={selectedLayerIds.has(layout.layer_id) ? "#38bdf8" : "#cbd5e1"}
            stroke="#64748b"
            strokeWidth="4"
          />
        ))}
        <rect className="mini-viewport" x={viewBox.x} y={viewBox.y} width={viewBox.width} height={viewBox.height} />
      </svg>
      <div className="relation-legend">
        <div className="panel-title">Legend</div>
        {(graph?.relation_styles ?? []).map((style) => {
          const preview = relationStroke(style.name, style);
          return (
            <div key={style.id} className="legend-row">
              <svg viewBox="0 0 74 16" aria-hidden="true">
                <defs>
                  <marker id={`legend-arrow-${style.id}`} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto" markerUnits="userSpaceOnUse">
                    <path d="M 0 0 L 7 3.5 L 0 7 z" fill={preview.stroke} />
                  </marker>
                </defs>
                <line
                  x1="4"
                  y1="8"
                  x2="66"
                  y2="8"
                  stroke={preview.stroke}
                  strokeWidth={Math.max(2, Math.min(4, preview.strokeWidth))}
                  strokeDasharray={preview.strokeDasharray}
                  markerEnd={style.marker_type === "arrow" ? `url(#legend-arrow-${style.id})` : undefined}
                />
              </svg>
              <span>{style.name}</span>
            </div>
          );
        })}
      </div>
    </section>
  );
}
