// frontend-vue/src/components/editor/PropertyPanel.vue
<script setup lang="ts">
import { computed } from "vue";
import { api } from "../../api/client";
import { isMergedLayer } from "../../domain/graph";
import { useAppStore } from "../../stores/app";
import { useGraphStore } from "../../stores/graph";
import { useProjectStore } from "../../stores/project";
import type { LayerUpdate, LayoutUpdate, PortName, RelationUpdate, StyleUpdate, TextBoxUpdate } from "../../types";

const app = useAppStore(); const graph = useGraphStore(); const project = useProjectStore();
const emit = defineEmits<{ collapse: [] }>();
const COLOR_SWATCHES = ["#ffffff", "#fef3c7", "#dbeafe", "#dcfce7", "#ffe4e6", "#e5e7eb", "#111827", "#2563eb", "#dc2626"];
const selectedLayers = computed(() => app.selection.filter((item) => item.kind === "layer").flatMap((item) => {
  const layer = graph.rawGraph?.layers.find((row) => row.id === item.id); return layer ? [layer] : [];
}));
const item = computed(() => app.selection.length === 1 ? app.selection[0] : null);
const layer = computed(() => selectedLayers.value.length === 1 ? selectedLayers.value[0] : null);
const canSplitLayer = computed(() => Boolean(
  layer.value && graph.rawGraph && isMergedLayer(graph.rawGraph, layer.value.id),
));
const layout = computed(() => layer.value ? graph.rawGraph?.layouts.find((row) => row.layer_id === layer.value!.id) : null);
const style = computed(() => layer.value ? graph.rawGraph?.styles.find((row) => row.layer_id === layer.value!.id) : null);
const relation = computed(() => item.value?.kind === "relation" ? graph.rawGraph?.relations.find((row) => row.id === item.value!.id) : null);
const text = computed(() => item.value?.kind === "text" ? graph.rawGraph?.text_boxes.find((row) => row.id === item.value!.id) : null);
async function updateLayer(body: LayerUpdate) { if (layer.value) await graph.mutateGraph("Layer 저장", () => api.updateLayer(project.projectId, layer.value!.id, body)) }
async function updateLayout(body: LayoutUpdate) { if (layer.value) await graph.mutateGraph("배치 저장", () => api.updateLayout(project.projectId, layer.value!.id, body)) }
async function updateStyle(body: StyleUpdate) { if (layer.value) await graph.mutateGraph("스타일 저장", () => api.updateStyle(project.projectId, layer.value!.id, body)) }
async function updateRelation(body: RelationUpdate) { if (relation.value) await graph.mutateGraph("관계 저장", () => api.updateRelation(project.projectId, relation.value!.id, body)) }
async function updateText(body: TextBoxUpdate) { if (text.value) await graph.mutateGraph("텍스트 저장", () => api.updateText(project.projectId, text.value!.id, body)) }
async function updateSelectedStyles(body: StyleUpdate) {
  if (!selectedLayers.value.length) return;
  await graph.mutateGraph("다중 스타일 저장", () => api.batchGraph(project.projectId, { styles: selectedLayers.value.map((row) => ({ layer_id: row.id, ...body })) }));
}
async function updateSelectedLayouts(body: LayoutUpdate) {
  await graph.mutateGraph("다중 배치 저장", () => api.batchGraph(project.projectId, { layouts: selectedLayers.value.map((row) => ({ layer_id: row.id, ...body })) }));
}
async function updateSelectedLayers(body: LayerUpdate) {
  await graph.mutateGraph("다중 Layer 저장", async () => {
    for (const row of selectedLayers.value) await api.updateLayer(project.projectId, row.id, body);
  });
}
function selectedPort(event: Event): PortName {
  const value = (event.target as HTMLSelectElement).value;
  return value === "top" || value === "right" || value === "bottom" || value === "left" ? value : "bottom";
}
function value(event: Event) { return (event.target as HTMLInputElement | HTMLTextAreaElement).value }
function numberValue(event: Event) { return Number((event.target as HTMLInputElement).value) }
</script>

<template>
  <aside class="property-panel">
    <div class="side-heading">
      <span>PROPERTIES</span>
      <div>
        <button v-if="app.selection.length" aria-label="선택 해제" title="선택 해제" @click="app.clearSelection()">×</button>
        <button class="panel-collapse-button" aria-label="Properties 패널 닫기" title="Properties 패널 닫기" @click="emit('collapse')">›</button>
      </div>
    </div>
    <fieldset class="property-fieldset" :disabled="!project.canEdit">
    <div v-if="selectedLayers.length > 1" class="property-form multi-property">
      <div class="property-title"><div><strong>{{ selectedLayers.length }} Layers</strong><small>다중 편집</small></div></div>
      <label>Fill<input type="color" value="#dbeafe" @change="updateSelectedStyles({ fill_color: value($event) })"></label>
      <div class="color-swatches"><button v-for="color in COLOR_SWATCHES" :key="color" class="color-swatch" :style="{ background: color }" @click="updateSelectedStyles({ fill_color: color })"/></div>
      <label>Stroke<input type="color" value="#2563eb" @change="updateSelectedStyles({ stroke_color: value($event) })"></label>
      <label>Text<input type="color" value="#111827" @change="updateSelectedStyles({ text_color: value($event) })"></label>
      <label>Font size<input type="number" min="8" max="72" value="16" @change="updateSelectedStyles({ font_size: numberValue($event) })"></label>
      <label>Width<input type="number" min="60" value="180" @change="updateSelectedLayouts({ width: numberValue($event) })"></label>
      <label>Height<input type="number" min="36" value="72" @change="updateSelectedLayouts({ height: numberValue($event) })"></label>
      <label>Align<input @change="updateSelectedLayers({ align: value($event) || null })"></label>
      <div class="property-split"/>
      <button @click="graph.mutateGraph('Layer 병합', () => api.merge(project.projectId, { layer_ids: selectedLayers.map(row => row.id) }))">Merge Layers</button>
    </div>
    <div v-else-if="layer" class="property-form">
      <div class="property-title"><span class="layer-dot"/><div><strong>{{ layer.name }}</strong><small>Layer</small></div></div>
      <label>이름<input :value="layer.name" @change="updateLayer({ name: value($event) })"></label>
      <label>Step<input :value="layer.step" @change="updateLayer({ step: value($event) || null })"></label>
      <label>Property<input :value="layer.layer_property" @change="updateLayer({ layer_property: value($event) || null })"></label>
      <label>Align<input :value="layer.align" @change="updateLayer({ align: value($event) || null })"></label>
      <label>Align Side<input :value="layer.align_side" @change="updateLayer({ align_side: value($event) || null })"></label>
      <label>Description<textarea :value="layer.description" @change="updateLayer({ description: value($event) || null })"/></label>
      <label>Group<input :value="layer.pending_group" @change="graph.mutateGraph('그룹 저장', () => api.updateGroup(project.projectId, layer!.id, value($event) || null))"></label>
      <div class="property-split"/>
      <label v-if="layout">X<input type="number" :value="layout.x" @change="updateLayout({ x: numberValue($event) })"></label><label v-if="layout">Y<input type="number" :value="layout.y" @change="updateLayout({ y: numberValue($event) })"></label>
      <label v-if="layout">Width<input type="number" min="60" :value="layout.width" @change="updateLayout({ width: numberValue($event) })"></label><label v-if="layout">Height<input type="number" min="36" :value="layout.height" @change="updateLayout({ height: numberValue($event) })"></label>
      <div class="property-split"/>
      <label v-if="style">Fill<input type="color" :value="style.fill_color" @change="updateStyle({ fill_color: value($event) })"></label><div v-if="style" class="color-swatches"><button v-for="color in COLOR_SWATCHES" :key="color" class="color-swatch" :style="{ background: color }" @click="updateStyle({ fill_color: color })"/></div>
      <label v-if="style">Stroke<input type="color" :value="style.stroke_color" @change="updateStyle({ stroke_color: value($event) })"></label><label v-if="style">Text<input type="color" :value="style.text_color" @change="updateStyle({ text_color: value($event) })"></label>
      <label v-if="style">Font size<input type="number" min="8" max="72" :value="style.font_size" @change="updateStyle({ font_size: numberValue($event) })"></label><label v-if="style">Stroke width<input type="number" min="1" max="12" :value="style.stroke_width" @change="updateStyle({ stroke_width: numberValue($event) })"></label>
      <button v-if="canSplitLayer" @click="graph.mutateGraph('Layer 분할', () => api.split(project.projectId, layer!.id))">Split Layer</button>
    </div>
    <div v-else-if="relation" class="property-form">
      <div class="property-title"><span class="relation-dot"/><div><strong>Relation</strong><small>{{ relation.id.slice(0, 8) }}</small></div></div>
      <label>Type<select :value="relation.relation_type" @change="updateRelation({ relation_type: value($event) })"><option v-for="type in ['parent_child','reference','optional','blocking','overlay']" :key="type">{{ type }}</option></select></label>
      <label>Instance<input :value="relation.instance" @change="updateRelation({ instance: value($event) || null })"></label>
      <label>Source<select :value="relation.source_port" @change="updateRelation({ source_port: selectedPort($event) })"><option v-for="port in ['top','right','bottom','left']" :key="port">{{ port }}</option></select></label>
      <label>Target<select :value="relation.target_port" @change="updateRelation({ target_port: selectedPort($event) })"><option v-for="port in ['top','right','bottom','left']" :key="port">{{ port }}</option></select></label>
      <label>Arrow<select :value="relation.relation_style_id || ''" @change="updateRelation({ relation_style_id: value($event) || null })"><option value="">기본</option><option v-for="row in graph.rawGraph?.relation_styles" :key="row.id" :value="row.id">{{ row.name }}</option></select></label>
      <p class="meta-box">Waypoints {{ relation.waypoints?.length ?? 0 }}개<br>Attached {{ relation.attached_relation_id ? relation.attached_relation_id.slice(0, 8) : '없음' }}</p>
    </div>
    <div v-else-if="text" class="property-form">
      <div class="property-title"><strong>Text Box</strong></div><label>텍스트<textarea :value="text.text" @change="updateText({ text: value($event) })"/></label>
      <label>X<input type="number" :value="text.x" @change="updateText({ x: numberValue($event) })"></label><label>Y<input type="number" :value="text.y" @change="updateText({ y: numberValue($event) })"></label>
      <label>Width<input type="number" min="40" :value="text.width" @change="updateText({ width: numberValue($event) })"></label><label>Height<input type="number" min="24" :value="text.height" @change="updateText({ height: numberValue($event) })"></label>
      <label>Font Size<input type="number" min="8" max="96" :value="text.font_size" @change="updateText({ font_size: numberValue($event) })"></label><label>Text Color<input type="color" :value="text.text_color" @change="updateText({ text_color: value($event) })"></label>
      <label>Background<input type="color" :value="text.background_color" @change="updateText({ background_color: value($event) })"></label><label>Border<input type="color" :value="text.border_color" @change="updateText({ border_color: value($event) })"></label>
      <label>Locked<input type="checkbox" :checked="text.locked" @change="updateText({ locked: ($event.target as HTMLInputElement).checked })"></label>
    </div>
    <div v-else class="property-empty"><div class="empty-icon">◇</div><b>선택된 객체가 없습니다.</b><p>Canvas에서 Layer, 관계선 또는 Text Box를 선택하세요.</p></div>
    </fieldset>
  </aside>
</template>

// frontend/src/components/PropertyPanel.tsx
import type { Graph, Layout, Relation, SelectionItem, ShapeStyle, TextBox } from "../types";

interface Props {
  graph: Graph | null;
  selection: SelectionItem[];
  onSelectionChange: (selection: SelectionItem[]) => void;
  onUpdateLayer: (layerId: string, payload: Record<string, unknown>) => Promise<void>;
  onUpdateStyle: (layerId: string, payload: Partial<ShapeStyle>) => Promise<void>;
  onUpdateLayout: (layerId: string, payload: Partial<Layout>) => Promise<void>;
  onUpdateRelation: (relationId: string, payload: Partial<Relation>) => Promise<void>;
  onUpdateTextBox: (textBoxId: string, payload: Partial<TextBox>) => Promise<void>;
}

const RELATION_TYPES = ["parent_child", "reference", "optional", "blocking"];
const COLOR_SWATCHES = ["#ffffff", "#fef3c7", "#dbeafe", "#dcfce7", "#ffe4e6", "#e5e7eb", "#111827", "#2563eb", "#dc2626"];

function ColorSwatches({ onPick }: { onPick: (color: string) => void }) {
  return (
    <div className="color-swatches">
      {COLOR_SWATCHES.map((color) => (
        <button
          key={color}
          type="button"
          className="color-swatch"
          style={{ backgroundColor: color }}
          title={color}
          onClick={() => onPick(color)}
        />
      ))}
    </div>
  );
}

export default function PropertyPanel({
  graph,
  selection,
  onSelectionChange,
  onUpdateLayer,
  onUpdateStyle,
  onUpdateLayout,
  onUpdateRelation,
  onUpdateTextBox
}: Props) {
  const selectedLayers = selection
    .filter((item) => item.kind === "layer")
    .map((item) => graph?.layers.find((layer) => layer.id === item.id))
    .filter(Boolean);
  const selectedLayerIds = selectedLayers.map((layer) => layer!.id);
  const selectedRelation = selection.length === 1 && selection[0].kind === "relation"
    ? graph?.relations.find((relation) => relation.id === selection[0].id)
    : null;
  const selectedText = selection.length === 1 && selection[0].kind === "text"
    ? graph?.text_boxes.find((textBox) => textBox.id === selection[0].id)
    : null;
  const singleLayer = selectedLayers.length === 1 ? selectedLayers[0] ?? null : null;
  const singleLayout = singleLayer ? graph?.layouts.find((layout) => layout.layer_id === singleLayer.id) : null;
  const singleStyle = singleLayer ? graph?.styles.find((style) => style.layer_id === singleLayer.id) : null;

  const updateManyStyles = (payload: Partial<ShapeStyle>) => {
    void Promise.all(selectedLayerIds.map((layerId) => onUpdateStyle(layerId, payload)));
  };

  if (!graph) {
    return (
      <aside className="property-panel">
        <div className="panel-title">Properties</div>
        <div className="empty-state">No project loaded.</div>
      </aside>
    );
  }

  return (
    <aside className="property-panel">
      <div className="panel-title">Properties</div>
      {selection.length === 0 && <div className="empty-state">Select a layer, relation, or text box.</div>}

      {selectedLayers.length > 1 && (
        <section className="property-section">
          <h2>{selectedLayers.length} Layers</h2>
          <label>
            Fill
            <input type="color" onChange={(event) => updateManyStyles({ fill_color: event.target.value })} />
          </label>
          <ColorSwatches onPick={(color) => updateManyStyles({ fill_color: color })} />
          <label>
            Line
            <input type="color" onChange={(event) => updateManyStyles({ stroke_color: event.target.value })} />
          </label>
          <ColorSwatches onPick={(color) => updateManyStyles({ stroke_color: color })} />
          <label>
            Text
            <input type="color" onChange={(event) => updateManyStyles({ text_color: event.target.value })} />
          </label>
          <ColorSwatches onPick={(color) => updateManyStyles({ text_color: color })} />
          <label>
            Font size
            <input type="number" min="8" max="72" onBlur={(event) => updateManyStyles({ font_size: Number(event.target.value) })} />
          </label>
        </section>
      )}

      {singleLayer && singleLayout && singleStyle && (
        <>
          <section className="property-section">
            <h2>Layer</h2>
            <label>
              Name
              <input
                defaultValue={singleLayer.name}
                onBlur={(event) => void onUpdateLayer(singleLayer.id, { name: event.target.value })}
              />
            </label>
            <label>
              Step
              <input
                defaultValue={singleLayer.step ?? ""}
                onBlur={(event) => void onUpdateLayer(singleLayer.id, { step: event.target.value || null })}
              />
            </label>
            <label>
              Property
              <input
                defaultValue={singleLayer.layer_property ?? ""}
                onBlur={(event) => void onUpdateLayer(singleLayer.id, { layer_property: event.target.value || null })}
              />
            </label>
            <label>
              Align
              <input
                defaultValue={singleLayer.align ?? ""}
                onBlur={(event) => void onUpdateLayer(singleLayer.id, { align: event.target.value || null })}
              />
            </label>
            <label>
              Align side
              <input
                defaultValue={singleLayer.align_side ?? ""}
                onBlur={(event) => void onUpdateLayer(singleLayer.id, { align_side: event.target.value || null })}
              />
            </label>
          </section>
          <section className="property-section">
            <h2>Shape Format</h2>
            <label>
              Fill
              <input type="color" value={singleStyle.fill_color} onChange={(event) => void onUpdateStyle(singleLayer.id, { fill_color: event.target.value })} />
            </label>
            <ColorSwatches onPick={(color) => void onUpdateStyle(singleLayer.id, { fill_color: color })} />
            <label>
              Line
              <input type="color" value={singleStyle.stroke_color} onChange={(event) => void onUpdateStyle(singleLayer.id, { stroke_color: event.target.value })} />
            </label>
            <ColorSwatches onPick={(color) => void onUpdateStyle(singleLayer.id, { stroke_color: color })} />
            <label>
              Text
              <input type="color" value={singleStyle.text_color} onChange={(event) => void onUpdateStyle(singleLayer.id, { text_color: event.target.value })} />
            </label>
            <ColorSwatches onPick={(color) => void onUpdateStyle(singleLayer.id, { text_color: color })} />
            <label>
              Font size
              <input
                type="number"
                min="8"
                max="72"
                value={singleStyle.font_size}
                onChange={(event) => void onUpdateStyle(singleLayer.id, { font_size: Number(event.target.value) })}
              />
            </label>
            <label>
              Width
              <input
                type="number"
                min="60"
                value={Math.round(singleLayout.width)}
                onChange={(event) => void onUpdateLayout(singleLayer.id, { width: Number(event.target.value) })}
              />
            </label>
            <label>
              Height
              <input
                type="number"
                min="36"
                value={Math.round(singleLayout.height)}
                onChange={(event) => void onUpdateLayout(singleLayer.id, { height: Number(event.target.value) })}
              />
            </label>
          </section>
        </>
      )}

      {selectedRelation && (
        <section className="property-section">
          <h2>Relation</h2>
          <label>
            Arrow style
            <select
              value={selectedRelation.relation_style_id ?? graph.relation_styles[0]?.id ?? ""}
              onChange={(event) => {
                const nextStyle = graph.relation_styles.find((style) => style.id === event.target.value);
                void onUpdateRelation(selectedRelation.id, {
                  relation_style_id: event.target.value,
                  relation_type: nextStyle?.name ?? selectedRelation.relation_type
                });
              }}
            >
              {graph.relation_styles.map((style) => (
                <option key={style.id} value={style.id}>{style.name}</option>
              ))}
            </select>
          </label>
          <label>
            Type
            <select
              value={selectedRelation.relation_type}
              onChange={(event) => void onUpdateRelation(selectedRelation.id, { relation_type: event.target.value })}
            >
              {RELATION_TYPES.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </label>
          <label>
            Source port
            <select
              value={selectedRelation.source_port}
              onChange={(event) => void onUpdateRelation(selectedRelation.id, { source_port: event.target.value as Relation["source_port"] })}
            >
              <option value="top">top</option>
              <option value="right">right</option>
              <option value="bottom">bottom</option>
              <option value="left">left</option>
            </select>
          </label>
          <label>
            Target port
            <select
              value={selectedRelation.target_port}
              onChange={(event) => void onUpdateRelation(selectedRelation.id, { target_port: event.target.value as Relation["target_port"] })}
            >
              <option value="top">top</option>
              <option value="right">right</option>
              <option value="bottom">bottom</option>
              <option value="left">left</option>
            </select>
          </label>
        </section>
      )}

      {selectedText && (
        <section className="property-section">
          <h2>Text Box</h2>
          <label>
            Text
            <textarea defaultValue={selectedText.text} onBlur={(event) => void onUpdateTextBox(selectedText.id, { text: event.target.value })} />
          </label>
          <label>
            Text color
            <input type="color" value={selectedText.text_color} onChange={(event) => void onUpdateTextBox(selectedText.id, { text_color: event.target.value })} />
          </label>
          <label>
            Font size
            <input type="number" min="8" max="96" value={selectedText.font_size} onChange={(event) => void onUpdateTextBox(selectedText.id, { font_size: Number(event.target.value) })} />
          </label>
          <label>
            Fill
            <input type="color" value={selectedText.background_color} onChange={(event) => void onUpdateTextBox(selectedText.id, { background_color: event.target.value })} />
          </label>
          <label>
            Border
            <input type="color" value={selectedText.border_color} onChange={(event) => void onUpdateTextBox(selectedText.id, { border_color: event.target.value })} />
          </label>
        </section>
      )}

      {selection.length > 0 && (
        <button type="button" className="clear-selection" onClick={() => onSelectionChange([])}>
          Clear Selection
        </button>
      )}
    </aside>
  );
}
