// frontend-vue/src/components/editor/Toolbar.vue
<script setup lang="ts">
import { ref } from "vue";
import { api } from "../../api/client";
import { cloneJson } from "../../domain/clone";
import { useAppStore } from "../../stores/app";
import { useGraphStore } from "../../stores/graph";
import { useProjectStore } from "../../stores/project";
import { useReferenceStore } from "../../stores/reference";
import type { LayerMaster } from "../../types";
import LayerMasterPickerModal from "./LayerMasterPickerModal.vue";

const app = useAppStore();
const graph = useGraphStore();
const project = useProjectStore();
const reference = useReferenceStore();
const addMenuOpen = ref(false);

async function addLayer() {
  const index = (graph.rawGraph?.layers.length ?? 0) + 1;
  await graph.mutateGraph("Layer 추가", () => api.createLayer(project.projectId, {
    name: `Layer ${index}`, x: 120 + index * 20, y: 100 + index * 20,
    box_preset_id: reference.selectedBoxPresetId || null,
  }));
}
async function addLayerFromMaster(master: LayerMaster) {
  app.layerMasterPickerOpen = false;
  const snapshot = cloneJson(master);
  await graph.mutateGraph("Layer 정보에서 추가", () => api.createLayer(project.projectId, {
    name: master.name,
    step: master.layer_number,
    x: 120 + (graph.rawGraph?.layers.length ?? 0) * 20,
    y: 120 + (graph.rawGraph?.layers.length ?? 0) * 20,
    box_preset_id: reference.selectedBoxPresetId || null,
    metadata_json: { layer_master: snapshot },
  }));
}
async function addText() { await graph.mutateGraph("텍스트 추가", () => api.createText(project.projectId, { text: "Text", x: 180, y: 160 })) }
function selectAll() { app.selection = graph.displayGraph?.layers.map((layer) => ({ kind: "layer" as const, id: layer.id })) ?? [] }
</script>

<template>
  <div class="editor-toolbar">
    <select v-model="reference.selectedRelationStyleId" aria-label="Arrow style"><option v-for="style in reference.relationStyles" :key="style.id" :value="style.id">{{ style.name }}</option></select>
    <span class="divider"/>
    <button :disabled="!graph.undoStack.length" @click="graph.undo">Undo</button><button :disabled="!graph.redoStack.length" @click="graph.redo">Redo</button>
    <span class="divider"/>
    <select v-model="reference.selectedBoxPresetId" aria-label="Box preset"><option v-for="preset in reference.boxPresets" :key="preset.id" :value="preset.id">{{ preset.name }}</option></select>
    <label class="toolbar-field">Label<select v-model="app.labelField"><option value="name">Layer</option><option value="step">Step</option></select></label>
    <button v-for="item in (['select','connect','text'] as const)" :key="item" :class="{ active: app.mode === item }" @click="app.mode = item">{{ item[0].toUpperCase() + item.slice(1) }}</button>
    <span class="divider"/>
    <div class="add-layer-split">
      <button @click="addLayer">Add Layer</button><button class="add-layer-caret" @click="addMenuOpen = !addMenuOpen">▾</button>
      <div v-if="addMenuOpen" class="add-layer-menu"><button @click="addLayer(); addMenuOpen = false">빈 Layer 추가</button><button @click="app.layerMasterPickerOpen = true; addMenuOpen = false">Layer정보에서 가져오기</button></div>
    </div>
    <button @click="addText">Add Text</button>
    <button :disabled="!graph.displayGraph?.layers.length" @click="selectAll">Select All</button>
    <button :disabled="app.selectedLayerIds.length < 2" @click="graph.mutateGraph('Layer 병합', () => api.merge(project.projectId, { layer_ids: app.selectedLayerIds }))">Merge</button>
    <button :disabled="!app.selectedSplitLayerId" @click="graph.mutateGraph('Layer 분할', () => api.split(project.projectId, app.selectedSplitLayerId!))">Split</button>
    <button :disabled="!project.projectId" @click="graph.mutateGraph('자동 배치', () => api.autoLayout(project.projectId))">Auto Layout</button>
    <button class="danger" :disabled="!app.selection.length" @click="graph.deleteSelection">Delete</button>
    <button @click="graph.reloadGraph">Refresh</button>
  </div>
  <LayerMasterPickerModal :open="app.layerMasterPickerOpen" @close="app.layerMasterPickerOpen = false" @confirm="addLayerFromMaster"/>
</template>

// frontend/src/components/Toolbar.tsx
import type { BoxPreset, EditorMode, RelationStyle } from "../types";

interface Props {
  mode: EditorMode;
  busy: boolean;
  status: string;
  projectId: string;
  relationStyles: RelationStyle[];
  selectedRelationStyleId: string;
  boxPresets: BoxPreset[];
  selectedBoxPresetId: string;
  selectedLayerCount: number;
  canUndo: boolean;
  canRedo: boolean;
  canSplitLayer: boolean;
  onRelationStyleChange: (styleId: string) => void;
  onBoxPresetChange: (presetId: string) => void;
  onCreateRelationStyle: () => void;
  onModeChange: (mode: EditorMode) => void;
  onCreateLayer: () => void;
  onCreateTextBox: () => void;
  onMergeLayers: () => void;
  onSplitLayer: () => void;
  onUndo: () => void;
  onRedo: () => void;
  onAutoLayout: () => void;
  onDelete: () => void;
  onRefresh: () => void;
}

export default function Toolbar({
  mode,
  busy,
  status,
  projectId,
  relationStyles,
  selectedRelationStyleId,
  boxPresets,
  selectedBoxPresetId,
  selectedLayerCount,
  canUndo,
  canRedo,
  canSplitLayer,
  onRelationStyleChange,
  onBoxPresetChange,
  onCreateRelationStyle,
  onModeChange,
  onCreateLayer,
  onCreateTextBox,
  onMergeLayers,
  onSplitLayer,
  onUndo,
  onRedo,
  onAutoLayout,
  onDelete,
  onRefresh
}: Props) {
  return (
    <header className="toolbar">
      <select value={selectedRelationStyleId} onChange={(event) => onRelationStyleChange(event.target.value)} aria-label="Arrow style">
        {relationStyles.map((style) => (
          <option key={style.id} value={style.id}>
            {style.name}
          </option>
        ))}
      </select>
      <button type="button" onClick={onCreateRelationStyle} disabled={!projectId}>Add Arrow</button>
      <div className="divider" />
      <button type="button" onClick={onUndo} disabled={!canUndo}>Undo</button>
      <button type="button" onClick={onRedo} disabled={!canRedo}>Redo</button>
      <div className="divider" />
      <select value={selectedBoxPresetId} onChange={(event) => onBoxPresetChange(event.target.value)} aria-label="Box preset">
        {boxPresets.map((preset) => (
          <option key={preset.id} value={preset.id}>
            {preset.name}
          </option>
        ))}
      </select>
      <button type="button" className={mode === "select" ? "active" : ""} onClick={() => onModeChange("select")}>
        Select
      </button>
      <button type="button" className={mode === "connect" ? "active" : ""} onClick={() => onModeChange("connect")}>
        Connect
      </button>
      <button type="button" className={mode === "text" ? "active" : ""} onClick={() => onModeChange("text")}>
        Text
      </button>
      <div className="divider" />
      <button type="button" onClick={onCreateLayer}>Add Layer</button>
      <button type="button" onClick={onCreateTextBox}>Add Text</button>
      <button type="button" onClick={onMergeLayers} disabled={selectedLayerCount < 2}>Merge Layers</button>
      <button type="button" onClick={onSplitLayer} disabled={!canSplitLayer}>Split Layer</button>
      <button type="button" onClick={onAutoLayout} disabled={!projectId}>Auto Layout</button>
      <button type="button" onClick={onDelete}>Delete</button>
      <button type="button" onClick={onRefresh}>Refresh</button>
      <div className="toolbar-status" data-busy={busy}>
        {busy ? "Saving..." : status}
      </div>
    </header>
  );
}
